config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('rosetta', include('rosetta.urls')),
    path('', include('posts.urls')),
    path('comments/', include('comments.urls')),
]

posts/urls.py
from django.urls import path
from posts import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('drafts', views.DraftPostListView.as_view(), name='draft_post_list'),
    path('search', views.search_view, name='search'),
    path('newpost', views.CreatePostView.as_view(), name='new_post'),
    path('<int:pk>', views.post_detail_view, name='post_detail'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<int:pk>', views.PostUpdateView.as_view(), name='post_update'),
]

comments/models.py
from django.db import models
from posts.models import Post
from django.contrib.auth import get_user_model


# Create your models here.
class Comment(models.Model):
    author = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE, related_name='comments',
                               verbose_name='نویسنده', null=False, blank=False)

    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, related_name='comments',
                             verbose_name='پست', null=False, blank=False)

    text = models.TextField(max_length=480, verbose_name='متن', null=False, blank=False)

    datetime_created = models.DateTimeField(auto_now_add=True, verbose_name='زمان نوشتن', null=False, blank=False)

    accepted = models.BooleanField(max_length=1, verbose_name='تایید شده', default=False,
                                 null=False, blank=False)
    checked = models.BooleanField(max_length=1, verbose_name='بررسی شده', default=False,
                                 null=False, blank=False)

    class Meta:
        verbose_name = 'کامنت'
        permissions = (('accept_comment','تایید کامنت'),)

    def __str__(self):
        return self.text[:20]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from ckeditor.fields import RichTextField


# Create your models here.
class Post(models.Model):
    STATUS_CHOICES = (
        ('pub', 'عمومی'),
        ('drf', 'پیش نویس')
    )

    title = models.CharField(max_length=90, null=False, blank=False, verbose_name='عنوان')
    description = models.TextField(max_length=600, verbose_name='توضیحات')
    body = RichTextField(verbose_name='بدنه')
    author = models.ForeignKey(get_user_model(), models.CASCADE, verbose_name='نویسنده')
    datetime_created = models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')
    datetime_modified = models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')
    status = models.CharField(choices=STATUS_CHOICES, max_length=3, verbose_name='حالت انتشار')

    class Meta:
        verbose_name = 'پست'
        permissions = (
            ("can_view_draft_post", "دیدن پست های پیش نویس"),)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from posts import models
from ckeditor.widgets import CKEditorWidget


# from tinymce.widgets import TinyMCE


class CreatePostForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = models.Post
        fields = ['title', 'description', 'body', 'status']

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import Http404
from allauth.account.utils import has_verified_email
from posts import forms, models
from comments.forms import CommentForm
from comments.models import Comment

# View for displaying a list of published posts
class PostListView(generic.ListView):
    model = models.Post
    context_object_name = 'posts'
    template_name = 'pages/post_list.html'
    paginate_by = 10

    def get_queryset(self):
        # Retrieve and return a queryset of published posts
        queryset = super(PostListView, self).get_queryset()
        return queryset.filter(status='pub').order_by('-datetime_created')


# View for displaying a list of draft posts (requires login and permission)
class DraftPostListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    model = models.Post
    context_object_name = 'posts'
    template_name = 'pages/post_list.html'
    permission_required = 'Post.delete_post'
    permission_denied_message = 'شما به این صفحه دسترسی ندارید'
    paginate_by = 10

    def get_queryset(self):
        # Retrieve and return a queryset of draft posts
        queryset = super(DraftPostListView, self).get_queryset()
        return queryset.filter(status='drf').order_by('-datetime_created')


# View for handling search functionality
def search_view(request):
    if request.method == 'POST':
        not_checked_comments = Comment.objects.filter(checked=False).order_by('-datetime_created')
        not_checked_comments_count = not_checked_comments.count()
        query = request.POST['search-query']
        # Filter posts based on the search query
        posts = models.Post.objects.filter(status='pub', title__contains=query)
        context = {
            'is_search': True,
            'search_query': str(query),
            'posts': posts,
            'not_checked_comments_count': not_checked_comments_count,
        }
        return render(request, 'pages/post_list.html', context)
    else:
        return redirect(reverse('home'))


# View for creating a new post (requires login and permission)
class CreatePostView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    form_class = forms.CreatePostForm
    template_name = 'pages/post_create.html'
    success_url = reverse_lazy('home')
    permission_required = 'posts.add_post'
    permission_denied_message = 'شما به این صفحه دسترسی ندارید'

    def has_permission(self):
        # Check if the user has verified their email and has permission
        has_access = super().has_permission()
        return has_access and has_verified_email(self.request.user, email=None)

    def get_success_url(self):
        success_url = reverse_lazy('post_detail', kwargs={'pk': self.object.pk})
        return str(success_url)

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, 'پست با موفقیت ساخته شد.')
        return super().form_valid(form)


# View for displaying post details and handling comments
def post_detail_view(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    comment_list = post.comments.filter(accepted=True).order_by('-datetime_created')
    not_checked_comments = Comment.objects.filter(checked=False).order_by('-datetime_created')
    not_checked_comments_count = not_checked_comments.count()
    if request.user.is_authenticated:
        email_verified = has_verified_email(request.user, email=None)
    else:
        email_verified = False
    if post.status == 'pub' or request.user.has_perm('posts.can_view_draft_post'):
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.post = post
                new_comment.author = request.user
                new_comment.save()
                messages.success(request, 'نظر شما ثبت شد و پس از تایید توسط مدیر وبسایت به نمایش در خواهد آمد. درصورت تایید یا رد نظر، شما ایمیلی دریافت خواهید کرد.')
                comment_form = CommentForm()
        else:
            comment_form = CommentForm()

        context = {
            'post': post,
            'comments': comment_list,
            'comment_form': comment_form,
            'not_checked_comments_count': not_checked_comments_count,
            'email_verified': email_verified,
        }
        return render(request, 'pages/post_detail.html', context)
    else:
        raise Http404


class PostDraftList(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    model = models.Post
    template_name = 'pages/post_list.html'
    permission_required = 'Post.can_view_draft_post'
    permission_denied_message = 'شما به این صفحه دسترسی ندارید'


# View for deleting a post (requires login and permission)
class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = models.Post
    template_name = 'pages/post_delete.html'
    success_url = reverse_lazy('home')
    permission_required = 'Post.delete_post'
    permission_denied_message = 'شما به این صفحه دسترسی ندارید'

    def has_permission(self):
        perms = self.get_permission_required()
        if self.request.user == self.get_object().author:
            return True
        else:
            return self.request.user.has_perms(perms)

    def form_valid(self, form):
        messages.success(self.request, 'پست با موفقیت ساخته شد')
        return super().form_valid(form)


# View for updating a post (requires login and permission)
class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = models.Post
    form_class = forms.CreatePostForm
    template_name = 'pages/post_create.html'
    success_url = reverse_lazy('post_detail', {'pk': 'self.object.pk'})
    permission_required = 'Post.update_post'
    permission_denied_message = 'شما به این صفحه دسترسی ندارید'
    extra_context = {
        'is_update': True,
    }

    def has_permission(self):
        perms = self.get_permission_required()
        if self.request.user == self.get_object().author:
            return True
        else:
            return self.request.user.has_perms(perms)

    def get_success_url(self):
        success_url = reverse_lazy('post_detail', kwargs={'pk': self.object.pk})
        return str(success_url)

    def form_valid(self, form):
        messages.success(self.request, 'پست با موفقیت ویرایش شد')
        return super().form_valid(form)

posts/templates/pages/post_create.html
{% extends '_base.html' %}
{% load static %}
{% block title %}
    {% if is_update %}
        ویرایش پست
    {% else %}
        ایجاد پست
    {% endif %}
{% endblock %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
        <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
        <p>
            <label for="id_title" class="form-label">عنوان:</label>
            <input type="text" class="form-control" name="title" maxlength="90" required="" id="id_title"{% if is_update %} value="{{ form.title.value }}"{% endif %}>
            <small id="char_count_title">0/90</small>
            <script>
                let titleInput = document.getElementById("id_title");
                let characterCounterTitle = document.getElementById("char_count_title");
                const maxNumOfCharsTitle = 90;
                const countCharactersTitle = () => {
                    let counterTitle = titleInput.value.length;
                    characterCounterTitle.textContent = counterTitle + "/" + maxNumOfCharsTitle;
                    if (counterTitle >= maxNumOfCharsTitle) {
                        characterCounterTitle.classList.add("text-danger");
                    } else {
                        characterCounterTitle.classList.remove("text-danger");
                    }
                };
                titleInput.addEventListener("input", countCharactersTitle);
            </script>
        </p>
        <p>
            <label for="id_description" class="form-label">توضیحات:</label>
            <textarea name="description" class="form-control" cols="40" rows="10" maxlength="600" required=""
                      id="id_description">{% if is_update %}{{ form.description.value }}{% endif %}</textarea>
            <small id="char_count_description">0/600</small>
            <script>
                let textArea = document.getElementById("id_description");
                let characterCounterDescription = document.getElementById("char_count_description");
                const maxNumOfCharsDescription = 600;
                const countCharactersDescription = () => {
                    let counter = textArea.value.length;
                    characterCounterDescription.textContent = counter + "/" + maxNumOfCharsDescription;
                    if (counter >= maxNumOfCharsDescription) {
                        characterCounterDescription.classList.add("text-danger");
                    } else {
                        characterCounterDescription.classList.remove("text-danger");
                    }
                };
                textArea.addEventListener("input", countCharactersDescription);
            </script>
        </p>
        <p><label for="id_body" class="form-label">بدنه پست:</label></p>
        {{ form.body }}
        <p>
            <label for="id_status">حالت انتشار:</label>
            <select name="status" class="form-select border border-3" required="" id="id_status">
                {% if form.status.value == 'pub' %}
                    <option value="pub">عمومی</option>
                    <option value="drf">پیش نویس</option>
                {% else %}
                    <option value="drf">پیش نویس</option>
                    <option value="pub">عمومی</option>
                {% endif %}
            </select>
        </p>
        <button type="submit" class="btn btn-success">ارسال</button>
    </form>

{% endblock %}

posts/templates/pages/post_delete.html
{% extends '_base.html' %}
{% block title %}
حذف {{ post.title }}
{% endblock %}
{% block body %}
    <h2>درحال حذف{{ post.title }}</h2>
{% endblock %}

posts/templates/pages/post_detail.html
{% extends '_base.html' %}
{% load jalali_tags %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block body %}
    <h1>{{ post.title }}</h1>
    <p><small>توسط {{ post.author.username }}</small> <small class="text-secondary">
        {% if post.datetime_modified == post.datetime_created %}نوشته شده در
            {{ post.datetime_created|to_jalali:'%d %B %Y' }}{% else %}ویرایش شده در
            {{ post.datetime_modified|to_jalali:'%d %B %Y' }}{% endif %}</small></p>

    <br><br>
    <p>{{ post.body|safe }}</p>
    <hr>

    <div>
        {% if perms.posts.delete_post or user == post.author %}
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
                حذف پست
            </button>
        {% endif %}
        {% if perms.posts.update_post or user == post.author %}
            <a class="btn btn-secondary" href="{% url 'post_update' post.pk %}">
                ویرایش پست
            </a>
        {% endif %}
    </div>


    {% if post.status == 'pub' %}
        <div class="mt-3">
        <h5>نظرات:</h5><br>
        {% if user.is_authenticated and email_verified %}
            <form method="POST">
                {% csrf_token %}
                <div>
                    <label for="id_text" class="form-label">نظر خود را بنویسید:</label>
                    <textarea class="form-control" name="text" cols="40" rows="10" maxlength="480" minlength="10"
                              required="" id="id_text"></textarea>
                    <small id="char_count">0/480</small>
                </div>
                <button type="submit" class="btn btn-outline-secondary">ثبت نظر</button>
            </form>
            <script>
                let textArea = document.getElementById("id_text");
                let characterCounter = document.getElementById("char_count");
                const maxNumOfChars = 480;
                const countCharacters = () => {
                    let counter = textArea.value.length;
                    characterCounter.textContent = counter + "/480";
                    if (counter >= maxNumOfChars) {
                        characterCounter.classList.add("text-danger");
                    } else {
                        characterCounter.classList.remove("text-danger");
                    }
                };
                textArea.addEventListener("input", countCharacters);
            </script>
        {% elif user.is_authenticated %}
            <h6>برای نظردادن، <a href="{% url 'account_email' %}" target="_blank">باید ایمیل خود را تایید کنید</a>.</h6>
        {% else %}
            <h6>برای نظر دادن، <a href="{% url 'account_login' %}">وارد شوید</a></h6>
        {% endif %}
        {% if comments|length > 0 %}


            {% for comment in comments %}
                <hr>
                <div>
                    <small>{{ comment.author.username }} در {{ comment.datetime_created|to_jalali:'%d %B %Y' }}
                        نوشت:</small>
                    <p>
                        {{ comment.text|linebreaks }}
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <p>هنوز نظری ثبت نشده است. اولین نفر باشید!</p>
        {% endif %}
    {% endif %}

</div>
    {% if perms.posts.delete_post or user == post.author %}

        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="deleteModalLabel">حذف پست</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        آیا مطمئنید که میخواهید پست {{ post.title }} را حذف کنید؟
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-bs-dismiss="modal">خیر</button>
                        <form action="{% url 'post_delete' post.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-danger">بله</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

posts/templates/pages/post_list.html
{% extends "_base.html" %}
{% block title %}خانه{% endblock %}
{% block body %}

    {% if is_search %}برای "{{ search_query }}" سرچ کردی{% endif %}
    {% if posts %}
        {% for post in posts %}
            <div>
                <div>
                    <a href="{% url 'post_detail' post.pk %}"><h3>{{ post.title }}</h3></a>
                </div>
                <p>
                    {{ post.description }}
                </p>
            </div>
            {% if forloop.counter < posts|length %}
                <hr>
            {% endif %}
        {% endfor %}
    {% else %}
        <h1>پستی پیدا نشد</h1>
    {% endif %}

{% endblock %}